### ISSUE TITLE
Chaingunners drop Maulers instead of Nailguns

### ISSUE THREAD

**Issue by XaserAcheron** [XaserAcheron/eriguns#31]
max-welp

**Comment by Talon1024** [comment]
This is why:
https://github.com/XaserAcheron/eriguns/blob/45ea3b04a8e930939d542cb75a7abc56bac6900b/eriguns2/zscript/eriguns2/weapons/mauler.txt#L7
https://github.com/XaserAcheron/eriguns/blob/45ea3b04a8e930939d542cb75a7abc56bac6900b/eriguns2/zscript/eriguns2/weapons/nailgun.txt#L7

Notice the Mauler replaces the chaingun instead of the Nailgun?

**Comment by XaserAcheron** [comment]
Finally got back around to this -- all fixed.

As a note, Maulers are supposed to replace chaingun _pickups_; the chaingunguy and backpack are meant to spawn Nailguns. This used to work as intended, but at some point I removed the mod's ChaingunGuy redefinition, and with it, the "DropItem Nailgun" line. Whoops! :P
